// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestingStuff.Models;

public partial class Contacts
{
    public int ContactId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? ContactTypeIdentifier { get; set; }

    public string FullName { get; set; }

    public virtual ICollection<ContactDevices> ContactDevices { get; } = new List<ContactDevices>();

    public virtual ContactType ContactTypeNavigation { get; set; }

    public virtual ICollection<Customers> Customers { get; } = new List<Customers>();
}