// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TestingStuff.Data;
using TestingStuff.Models;

namespace TestingStuff.Data.Configurations
{
    public partial class TerritoriesConfiguration : IEntityTypeConfiguration<Territories>
    {
        public void Configure(EntityTypeBuilder<Territories> entity)
        {
            entity.HasKey(e => e.TerritoryId).IsClustered(false);

            entity.HasIndex(e => e.RegionId, "IX_Territories_RegionID");

            entity.Property(e => e.TerritoryId)
            .HasMaxLength(20)
            .HasColumnName("TerritoryID");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.TerritoryDescription)
            .IsRequired()
            .HasMaxLength(50)
            .IsFixedLength();

            entity.HasOne(d => d.Region).WithMany(p => p.Territories)
            .HasForeignKey(d => d.RegionId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Territories_Region");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Territories> entity);
    }
}
